name: react-native-android-build-apk
on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: yarn install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          envkey_OAUTH_WEB_CLIENT_ID: ${{ secrets.OAUTH_WEB_CLIENT_ID }}
          envKey_API_ENDPOINT: 'https://api.stage.st-retrospect.dh-center.ru'
          envKey_VK_APP_ID: ${{ secrets.VK_APP_ID }}

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'beta'
          subdirectory: 'ios'


