name: react-native-build-ios
on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: yarn install

      - name: Make envfile
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ENV_OAUTH_WEB_CLIENT_ID: ${{ secrets.OAUTH_WEB_CLIENT_ID }}
          ENV_API_ENDPOINT: 'https://api.stage.st-retrospect.dh-center.ru'
          ENV_VK_APP_ID: ${{ secrets.VK_APP_ID }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'beta'
          subdirectory: 'ios'


