name: react-native-android-build-apk
on: [push]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: yarn install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          envkey_OAUTH_WEB_CLIENT_ID: ${{ secrets.OAUTH_WEB_CLIENT_ID }}
          envKey_API_ENDPOINT: 'https://api.stage.st-retrospect.dh-center.ru'

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Send prod release to the channel
        if: endsWith(github.ref, '/prod')
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New release!
          document: android/app/build/outputs/apk/release/app-release.apk

      - name: Send stage release to the chat
        if: endsWith(github.ref, '/stage')
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_DEV_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New Que.St *stage* release!
          document: android/app/build/outputs/apk/release/app-release.apk
