name: react-native-android-build-apk
on: [push]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          envkey_OAUTH_ANDROID_CLIENT_ID: ${{ secrets.OAUTH_ANDROID_CLIENT_ID }}
          envKey_API_ENDPOINT: 'https://api.stage.st-retrospect.dh-center.ru'


      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - uses: nelonoel/branch-name@v1
      - name: Send release to the channel
        if: endsWith(github.ref, '/master') || endsWith(github.ref, '/stage')
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New *${{env.BRANCH_NAME}}* release!
          document: android/app/build/outputs/apk/release/app-release.apk
